### ISSUE TITLE
增加 `updateCustomDomain` append routes 方案

### ISSUE THREAD

**Issue by bingtsingw** [devsapp/fc-api#11]
目前通过 `s cli fc-api updateCustomDomain --region xx --domainName xx --routeConfig xxx`可以更新域名, 但是其中的 routeConfig会被完全覆盖, CI环境下, 在shell里先取 `getCustomDomain` 的 `yml` 结果, 再转换成 `json` 拼接感觉有点麻烦, 不知道官方能不能提供相应支持, 比如增加一个 `--appendRoutes` 参数或者提供一个新的API

**Comment by bingtsingw** [comment]
API建议, 增加一个 `--routeConfigAppend` 的参数

`--routeConfig` 的调用方式保持不变:
`--routeConfig '{"routes":[{"path":"xx","serviceName":"xx","functionName":"xx","qualifier":"xx","methods":["GET","POST","PUT","DELETE","HEAD","PATCH"]}]}'`

`--routeConfigAppend` 的调用方式稍作修改, 去掉前面的`routes:`, 直接传入`Route`对象或者`Route[]`数组:
`--routeConfigAppend '{"path":"xx","serviceName":"xx","functionName":"xx","qualifier":"xx","methods":["GET","POST","PUT","DELETE","HEAD","PATCH"]}'`

**Comment by anycodes** [comment]
感谢建议。这个稍后晚一些给解决方案。

**Comment by anycodes** [comment]
请参考新版本：https://github.com/devsapp/fc-api/releases/tag/0.0.33

您可以在本地客户端直接使用，系统会自动更新这个组件
