### ISSUE TITLE
公网域名服务器下无法直接访问localhost下的资源

### ISSUE THREAD

**Issue by Laura-monkey** [devsapp/fc-api#8]
我使用云端私网的CENTOS的ECS，https://ecs-workbench.aliyun.com/view/instance/single/xxxxxxxx
使用s metrics查看指标的时候，起的是localhost:3000，但是在ECS上无法启动查看。
![image](https://user-images.githubusercontent.com/85347842/124489986-2bad6d00-dde4-11eb-8e47-5ae008ef0eef.png)

![image](https://user-images.githubusercontent.com/85347842/124489738-e8eb9500-dde3-11eb-934c-29bb3fcadfb5.png)

**Comment by hanxie-crypto** [comment]
linux 无gui 的系统确实还没法去查看这些指标，可以考虑做一个转发函数，通过转发函数提供的公共域名访问
